name: dwhich
version: 2.0.1
description: An extended version of the which command that also validates your PATH and indicates if the command is found in multiple locations on your PATH.\n
repository: https://github.com/onepub-dev/dwhich.git
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.7.0
  dcli: ^8.2.0
  path: ^1.9.1
  
dev_dependencies:
  lint_hard: ^6.2.1
executables:
  dwhich:
